### ISSUE TITLE
经测试，文档中好像有个问题

### ISSUE THREAD

**Issue by wangfeiping** [hainingzhang/articles#2]
原文：
peer chaincode upgrade -o orderer.example.com:7050 --tls --cafile $ORDERER_CA -n mycc -v 2.0 -c '{"Args":["init","c", "10", "d","20"]}'
修改：
peer chaincode upgrade -o orderer.example.com:7050 --tls --cafile $ORDERER_CA -C mychannel -n mycc -v 2.0 -c '{"Args":["init","c", "10", "d","20"]}'

**Comment by dawnjin** [comment]
2017-07-13 07:58:56.902 UTC [grpc] Printf -> DEBU 007 Failed to dial orderer.example.com:7050: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"; please retry.
Error: Error connecting due to  rpc error: code = Internal desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
在vm1执行“在工作目录下输入以下命令,创建名为 mychannel 的 channel:”的时候遇见上面的错误是为什么？

**Comment by jiahaoc1993** [comment]
把所有vm的crypto-config目录删除，在任一vm重新生成crypto-config后，把该新生成的目录拷贝到其他vm上

**Comment by hainingzhang** [comment]
@wangfeiping corrected. Thanks.
